##########################  配置mybatis ##########################
spring:
  profiles:
    active: prod  #默认为开发环境dev  生产环境需要更换为prod
server:
  port: 8080
  servlet:
    context-path: /myblogs

##########################  配置mybatis ##########################
mybatis:
  mapper-locations: classpath*:com/xk/myblogs/service/mapper/xml/*.xml

##########################  跨域配置参数  ##########################
CROS_MAPPING: /**
CROS_ALLOWED_HEADERS: /*
CROS_ALLOWED_ORIGINS: /*
CROS_ALLOWED_METHOD: OPTIONS,GET,POST,DELETE,PUT

##########################  配置jwt参数  ##########################
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  tokenHead: Bearer
  secret: oursecret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60)

##########################  自定义redis key ##########################
redis:
  key:
    prefix:
      authCode: "portal:authCode:" #验证码前缀
      authToken: "refresh_token:"  #token缓存时间
    expire:
      authCode: 120 #验证码超期时间
      authToken: 10800 #token刷新时间 三倍过期时长


