##########################  配置mybatis ##########################
spring:
  profiles:
    active: prod  #默认为开发环境dev  生产环境需要更换为prod
  ##########################  配置spring缓存 ##########################
  cache:
    type: REDIS
    cache-names: redisCache
    redis:
      use-key-prefix: false #禁用前缀
      cache-null-values: true #允许保存空值
      key-prefix:  #自定义前缀
      time-to-live: 60000 #一分钟
  ########################  配置MongoDB数据库 uri配置账号密码  ############################
  # 需要用户名和密码认证
  #uri:  mongodb://username:password@ip:port/admin
  #不需要用户名和密码认证
  #uri:  mongodb://ip:port/admin
  data:
    mongodb:
      uri: mongodb://myblogs:111@39.107.247.2:27017/myblogs

  # 配置activemq #
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: activeqmadmin
    pool:
      #是否启用连接池
      enabled: true
      max-connections: 50 #最大连接数量
    packages:
      trust-all: true
    #trusted: com.xk.myblogs.client.entity.nosql,java.lang 配置需要信任的包 Lang属于对象 也需要配置#
  # 配置jms连接池 #
  jms:
    pub-sub-domain: true #是否使用发布订阅模式 默认为false 即点对点
    template:
      default-destination: activemq.default.destination #默认目的地址

server:
  port: 8080
  servlet:
    context-path: /myblogs

##########################  配置mybatis ##########################
mybatis:
  mapper-locations:
    - classpath*:com/xk/myblogs/service/mapper/xml/*.xml
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.xk.myblogs.service.typehandler

##########################  跨域配置参数  ##########################
CROS_MAPPING: /**
CROS_ALLOWED_HEADERS: /*
CROS_ALLOWED_ORIGINS: /*
CROS_ALLOWED_METHOD: OPTIONS,GET,POST,DELETE,PUT

##########################  配置jwt参数  ##########################
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  tokenHead: Bearer
  secret: oursecret #JWT加解密使用的密钥
  expiration: 15000 #JWT的超期限时间(60*60)

##########################  自定义redis key ##########################
redis:
  key:
    prefix:
      authCode: "portal:authCode:" #验证码前缀
      authToken: "refresh_token:"  #token缓存时间
    expire:
      authCode: 120 #验证码超期时间
      authToken: 3000 #token刷新时间 三倍过期时长

logging:
  level:
    org.springframework.data.mongodb.core: debug
